# This file controls the settings for Quarto template inspired from www.marvinschmitt.com

# website settings
website:
  title: "Hazman Naim"  # name
  description: "Physics Graduate & Aspiring Data Scientist | Data Science, Data Analysis, Research | Explore my journey 🔭"   # A brief slogan (optional)
  image: img/my_image.jpg
  favicon: img/logo_data.jpeg
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo_data.jpeg
    
    # Sub-pages
    left:
      - text: "About Me"
        href: about/index.qmd
      #- text: "Projects"
        #href: projects/index.qmd
      - text: "CV"
        href: cv/index.qmd    
      - text: "NeuralBites"
        href: blog/index.qmd
    
    # Social media handles
    right:
      - icon: github
        href: https://github.com/HazmanNaim
      - icon: linkedin
        href: https://www.linkedin.com/in/hazmannaim/
      - icon: envelope
        aria-label: email
        href: "mailto:hazmannaimbinahsan@gmail.com"
      - icon: window-fullscreen
        href: https://www.kaggle.com/hazmannaim
  
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 Hazman Naim CC BY-SA 4.0</span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block"><a href="https://github.com/HazmanNaim/HazmanNaim.github.io">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true