project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"

website:
  title: "Hazman Naim"
  site-url: "https://hazmannaim.github.io"
  search: false
  navbar:
    background: "#536878"
    left:
      - href: about/index.qmd
        text: About
  page-footer:
    left: "Copyright 2025, Hazman Naim"
    right:
      - icon: github
        href: https://github.com/HazmanNaim
      - icon: linkedin
        href: https://linkedin.com/in/hazmannaim
    background: "#536878"

date-format: "D MMMM YYYY"

format:
  html:
    theme: tango
    css: styles.css
    toc: false
    html-math-method: katex
    include-in-header:
      file: header.html
