---
title: "Get to Know Me!"
pagetitle: "{{< meta website.title >}}"
main-photo: /img/hazman_image.jpg
main-photo-square: /img/hazman_image.jpg
title-block-banner: "#771C6D"
format:
  html:
    quarto-template-params:
      banner-header-class: "home"
toc: true
toc-location: left
toc-title: "Contents"
---

# About

> "Develop a passion for learning. If you do, you will never cease to grow." - Anthony J. D'Angelo

I have a genuine passion for learning because I believe it's the key to personal growth. To me, knowledge is akin to a precious gem -- valuable and capable of making a positive impact on the world. This mindset has turned me into a naturally curious individual, always eager to acquire and refine skills, with a particular focus on Python, data science, machine learning, and AI.

My background in Physics has instilled in me the importance of understanding the fundamental principles that drive algorithms. I don't settle for simply copying and pasting code; I strive for a deeper comprehension of how things work.

> "The only way to grow is to challenge yourself." - Ashley Tisdale

This quote deeply resonates with me. Building on this philosophy, I've come to understand that the only way to truly grow is by challenging oneself. This realization has motivated me to actively explore unfamiliar territories. I eagerly embrace new opportunities, extending beyond my comfort zone.

In addition to my core focus on Python, data science, machine learning, and AI, I have explored into diverse domains. For instance, I've ventured into natural sciences like genetics and biology. Simultaneously, I've explored linguistic domains, utilizing natural language processing to navigate the intricacies of language. Furthermore, I've not shied away from delving into business-related applications, broadening the scope of my knowledge and skills. In addition, I also participate in various data science competitions. These experiences continually push me to improve and evolve.

# Experience

**AI Developer \| October 2023 - Present**

[Renaissance AI]{.underline}

-   Led Research and Development team, innovating and implementing AI technologies for various applications, including product embedding and the development of a speech-to-text application.
-   Engineered a recommender system architecture for the backend of an e-commerce platform, optimising product recommendations and improving user experience through the integration of reinforcement learning.
-   Collaborated with a cross-functional AI backend team to analyse business requirements, skillfully translating them into scalable and efficient AI solutions that significantly contributed to client satisfaction.

# Education

**Universiti Malaya \| September 2019 - March 2023**

[Bachelor of Science in Physics]{.underline}

-   Passed with Honour
-   CGPA: 3.68

**Universiti Malaya \| September 2018 - June 2019**

[Physical Science]{.underline}

-   Chemistry, Additional Mathematics, Mathematics, Physics, Programming
-   CGPA: 4.00

# Skills

[**Programming Languages:**]{.underline}

-   Python
-   C
-   SQL

[**Tools:**]{.underline}

-   PyTorch
-   TensorFlow
-   Scikit-Learn
-   Flask
-   MySQL

# Open Source Contributions

-   [Mesolitica-Malaysian Dataset](https://github.com/mesolitica/malaysian-dataset) - Scraped websites to collect over 1 MB of text data for Malaysian language Large Language Model.

# Awards

-   Gold Honour - International Astronomy Astrophysics Competition 2021

# Courses and Certificates

-   General Assembly - Data Scientist Bootcamp \[[Link](https://github.com/HazmanNaim/General-Assembly-Data-Analytics-and-Data-Science)\]
-   IBM AI Engineering Professional Certificate \[[Link](https://github.com/HazmanNaim/IBM-AI-Engineering-Professional-Certificate)\]
-   IBM Data Science Professional Certificate \[[Link](https://github.com/HazmanNaim/IBM-Data-Science-Professional-Certificate)\]
-   KPMG AU Data Analytics Virtual Internship \[[Link](https://github.com/HazmanNaim/kpmg-virtual-internship)\]

# Activities

-   Kaggle-Binary Prediction of Smoker Status using Bio-Signals (Top 28%) \[[Link](https://www.kaggle.com/code/hazmannaim/binary-classification-weighted-ensemble-top-28)\]
-   Kaggle-Binary Classification with a Software Defects Dataset (Top 36%) \[[Link](https://www.kaggle.com/code/hazmannaim/software-defect-prediction-simple-ml-ensemble)\]
-   Kaggle-Predict Health Outcomes of Horses (Top 76%)

# Interests

In addition to my work as an AI Developer, I have a passion for astrophotography. I own a computerized telescope that is specifically designed for astrophotography. I capture images of deep sky objects, planets, and galaxies. I share these images on my Facebook page. I also enjoy participating in astronomy outreach programs. Recently, I had the opportunity to serve as a telescope operator for the Kuala Kubu Bharu Starfest 2023, which was organized by Majlis Daerah Hulu Selangor in collaboration with Sahabat Langit Utara.
